---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%",
  eval = FALSE
)
```

# Curso: Boas Práticas e Ferramentas da Ciência Aberta na Ecologia  

Este curso tratará de conceitos e ferramentas computacionais utilizadas para garantir a execução de projetos reprodutíveis
    em Ecologia e Evolução. Nele trataremos dos seguintes tópicos:
    
- Ciência aberta: motivação, tendências e razões para práticas científicas abertas. 

- A importância dos dados em ecologia: valorização, organização e publicação.

- Reprodutibilidade científica e reprodutibilidade computacional como fundamento básico de qualquer investigação científica.

- Ferramentas de controle de versão para código de análises de dados (git, GitHub) e ferramentas para escrita de relatórios (material suplementar, websites, livros, vinhetas) e códigos em R (Rmarkdown/Quarto). 

- Outras ferramentas para assegurar reprodutibilidade computacional das análises: dockers/containers, e pacotes em R. 

- Repositórios online e o DOI (Digital Object Identifier): tipos de repositórios para dados, análises e manuscritos (PrePrints). 

- Outras tendências em ecologia e ciência aberta: ética em publicação científica, pré-registro de projetos, entre outros

Este repositório contém o códigos fonte e dados que serão utilizados durante o curso. As atividades práticas e exercícios de apoio podem ser 
    encontradas neste [sítio](https://gabrielnakamura.github.io/USP_reproducibility_BIE5798/) 
    
Slides de aulas teóricas podem ser acessados [aqui](https://gabrielnakamura.github.io/USP_BIE5798_apresentacoes/)


# Responsáveis pela disciplina

[Melina Leite](https://melinaleite.weebly.com/) e [Gabriel Nakamura](https://main--gabrielnakamura.netlify.app/)







